// Progressive: true  -> Advancement
//              false -> Priority
//              null  -> Normal
//    Item:                                            [type, Progressive, GetItemID, special],
const item_table = {
    'Bombs [5]':                                       ['Item',     null,  0x01, null],
    'Deku Nuts [5]':                                   ['Item',     null,  0x02, null],
    'Bombchus [10]':                                   ['Item',     true,  0x03, null],
    'Boomerang':                                       ['Item',     true,  0x06, null],
    'Deku Stick [1]':                                  ['Item',     null,  0x07, null],
    'Lens of Truth':                                   ['Item',     true,  0x0A, null],
    'Megaton Hammer':                                  ['Item',     true,  0x0D, null],
    'Cojiro':                                          ['Item',     true,  0x0E, null],
    'Bottle':                                          ['Item',     true,  0x0F, {'bottle': 10000}],
    'Bottle with Milk':                                ['Item',     true,  0x14, {'bottle': 10000}],
    'Rutos Letter':                                    ['Item',     true,  0x15, null],
    'Deliver Letter':                                  ['Item',     true,  null, {'bottle': 10000}],
    'Sell Big Poe':                                    ['Item',     true,  null, {'bottle': 10000}],
    'Magic Bean':                                      ['Item',     true,  0x16, null],
    'Skull Mask':                                      ['Item',     null,  0x17, null],
    'Spooky Mask':                                     ['Item',     null,  0x18, null],
    'Keaton Mask':                                     ['Item',     null,  0x1A, null],
    'Bunny Hood':                                      ['Item',     null,  0x1B, null],
    'Mask of Truth':                                   ['Item',     null,  0x1C, null],
    'Pocket Egg':                                      ['Item',     true,  0x1D, null],
    'Pocket Cucco':                                    ['Item',     true,  0x1E, null],
    'Odd Mushroom':                                    ['Item',     true,  0x1F, null],
    'Odd Potion':                                      ['Item',     true,  0x20, null],
    'Poachers Saw':                                    ['Item',     true,  0x21, null],
    'Broken Sword':                                    ['Item',     true,  0x22, null],
    'Prescription':                                    ['Item',     true,  0x23, null],
    'Eyeball Frog':                                    ['Item',     true,  0x24, null],
    'Eyedrops':                                        ['Item',     true,  0x25, null],
    'Claim Check':                                     ['Item',     true,  0x26, null],
    'Kokiri Sword':                                    ['Item',     true,  0x27, null],
    'Giants Knife':                                    ['Item',     true,  0x28, null],
    'Deku Shield':                                     ['Item',     null,  0x29, null],
    'Hylian Shield':                                   ['Item',     null,  0x2A, null],
    'Mirror Shield':                                   ['Item',     true,  0x2B, null],
    'Goron Tunic':                                     ['Item',     true,  0x2C, null],
    'Zora Tunic':                                      ['Item',     true,  0x2D, null],
    'Iron Boots':                                      ['Item',     true,  0x2E, null],
    'Hover Boots':                                     ['Item',     true,  0x2F, null],
    'Stone of Agony':                                  ['Item',     true,  0x39, null],
    'Gerudo Membership Card':                          ['Item',     true,  0x3A, null],
    'Heart Container':                                 ['Item',     null,  0x3D, null],
    'Piece of Heart':                                  ['Item',     null,  0x3E, null],
    'Boss Key':                                        ['BossKey',  true,  0x3F, null],
    'Compass':                                         ['Compass',  null,  0x40, null],
    'Map':                                             ['Map',      null,  0x41, null],
    'Small Key':                                       ['SmallKey', true,  0x42, {'progressive': 10000}],
    'Weird Egg':                                       ['Item',     true,  0x47, null],
    'Recovery Heart':                                  ['Item',     null,  0x48, null],
    'Arrows [5]':                                      ['Item',     null,  0x49, null],
    'Arrows [10]':                                     ['Item',     null,  0x4A, null],
    'Arrows [30]':                                     ['Item',     null,  0x4B, null],
    'Rupee [1]':                                       ['Item',     null,  0x4C, null],
    'Rupees [5]':                                      ['Item',     null,  0x4D, null],
    'Rupees [20]':                                     ['Item',     null,  0x4E, null],
    'Heart Container [Boss]':                          ['Item',     null,  0x4F, null],
    'Milk':                                            ['Item',     null,  0x50, null],
    'Goron Mask':                                      ['Item',     null,  0x51, null],
    'Zora Mask':                                       ['Item',     null,  0x52, null],
    'Gerudo Mask':                                     ['Item',     null,  0x53, null],
    'Rupees [50]':                                     ['Item',     null,  0x55, null],
    'Rupees [200]':                                    ['Item',     null,  0x56, null],
    'Biggoron Sword':                                  ['Item',     true,  0x57, null],
    'Fire Arrows':                                     ['Item',     true,  0x58, null],
    'Ice Arrows':                                      ['Item',     true,  0x59, null],
    'Light Arrows':                                    ['Item',     true,  0x5A, null],
    'Gold Skulltula Token':                            ['Token',    true,  0x5B, {'progressive': 10000}],
    'Dins Fire':                                       ['Item',     true,  0x5C, null],
    'Nayrus Love':                                     ['Item',     true,  0x5E, null],
    'Farores Wind':                                    ['Item',     true,  0x5D, null],
    'Deku Nuts [10]':                                  ['Item',     null,  0x64, null],
    'Bombs [10]':                                      ['Item',     null,  0x66, null],
    'Bombs [20]':                                      ['Item',     null,  0x67, null],
    'Deku Seeds [30]':                                 ['Item',     null,  0x69, null],
    'Bombchus [5]':                                    ['Item',     true,  0x6A, null],
    'Bombchus [20]':                                   ['Item',     true,  0x6B, null],
    'Rupee [Treasure Chest Game]':                     ['Item',     null,  0x72, null],
    'Piece of Heart [Treasure Chest Game]':            ['Item', null,  0x76, null],
    'Ice Trap':                                        ['Item',     null,  0x7C, null],
    'Progressive Hookshot':                            ['Item',     true,  0x80, {'progressive': 2}],
    'Progressive Strength Upgrade':                    ['Item',     true,  0x81, {'progressive': 3}],
    'Bomb Bag':                                        ['Item',     true,  0x82, null],
    'Bow':                                             ['Item',     true,  0x83, null],
    'Slingshot':                                       ['Item',     true,  0x84, null],
    'Progressive Wallet':                              ['Item',     true,  0x85, {'progressive': 3}],
    'Progressive Scale':                               ['Item',     true,  0x86, {'progressive': 2}],
    'Deku Nut Capacity':                               ['Item',     null,  0x87, null],
    'Deku Stick Capacity':                             ['Item',     null,  0x88, null],
    'Bombchus':                                        ['Item',     true,  0x89, null],
    'Magic Meter':                                     ['Item',     true,  0x8A, null],
    'Ocarina':                                         ['Item',     true,  0x8B, null],
    'Bottle with Red Potion':                          ['Item',     true,  0x8C, {'bottle': true, 'shop_object': 0x0F}],
    'Bottle with Green Potion':                        ['Item',     true,  0x8D, {'bottle': true, 'shop_object': 0x0F}],
    'Bottle with Blue Potion':                         ['Item',     true,  0x8E, {'bottle': true, 'shop_object': 0x0F}],
    'Bottle with Fairy':                               ['Item',     true,  0x8F, {'bottle': true, 'shop_object': 0x0F}],
    'Bottle with Fish':                                ['Item',     true,  0x90, {'bottle': true, 'shop_object': 0x0F}],
    'Bottle with Blue Fire':                           ['Item',     true,  0x91, {'bottle': true, 'shop_object': 0x0F}],
    'Bottle with Bugs':                                ['Item',     true,  0x92, {'bottle': true, 'shop_object': 0x0F}],
    'Bottle with Big Poe':                             ['Item',     true,  0x93, {'shop_object': 0x0F}],
    'Bottle with Poe':                                 ['Item',     true,  0x94, {'bottle': true, 'shop_object': 0x0F}],
    'Boss Key [Forest Temple]':                        ['BossKey',  true,  0x95, null],
    'Boss Key [Fire Temple]':                          ['BossKey',  true,  0x96, null],
    'Boss Key [Water Temple]':                         ['BossKey',  true,  0x97, null],
    'Boss Key [Spirit Temple]':                        ['BossKey',  true,  0x98, null],
    'Boss Key [Shadow Temple]':                        ['BossKey',  true,  0x99, null],
    'Boss Key [Ganons Castle]':                        ['GanonBossKey',true,0x9A,null],
    'Compass [Deku Tree]':                             ['Compass',  null,  0x9B, null],
    'Compass [Dodongos Cavern]':                       ['Compass',  null,  0x9C, null],
    'Compass [Jabu Jabus Belly]':                      ['Compass',  null,  0x9D, null],
    'Compass [Forest Temple]':                         ['Compass',  null,  0x9E, null],
    'Compass [Fire Temple]':                           ['Compass',  null,  0x9F, null],
    'Compass [Water Temple]':                          ['Compass',  null,  0xA0, null],
    'Compass [Spirit Temple]':                         ['Compass',  null,  0xA1, null],
    'Compass [Shadow Temple]':                         ['Compass',  null,  0xA2, null],
    'Compass [Bottom of the Well]':                    ['Compass',  null,  0xA3, null],
    'Compass [Ice Cavern]':                            ['Compass',  null,  0xA4, null],
    'Map [Deku Tree]':                                 ['Map',      null,  0xA5, null],
    'Map [Dodongos Cavern]':                           ['Map',      null,  0xA6, null],
    'Map [Jabu Jabus Belly]':                          ['Map',      null,  0xA7, null],
    'Map [Forest Temple]':                             ['Map',      null,  0xA8, null],
    'Map [Fire Temple]':                               ['Map',      null,  0xA9, null],
    'Map [Water Temple]':                              ['Map',      null,  0xAA, null],
    'Map [Spirit Temple]':                             ['Map',      null,  0xAB, null],
    'Map [Shadow Temple]':                             ['Map',      null,  0xAC, null],
    'Map [Bottom of the Well]':                        ['Map',      null,  0xAD, null],
    'Map [Ice Cavern]':                                ['Map',      null,  0xAE, null],
    'Small Key [Forest Temple]':                       ['SmallKey', true,  0xAF, {'progressive': 10000}],
    'Small Key [Fire Temple]':                         ['SmallKey', true,  0xB0, {'progressive': 10000}],
    'Small Key [Water Temple]':                        ['SmallKey', true,  0xB1, {'progressive': 10000}],
    'Small Key [Spirit Temple]':                       ['SmallKey', true,  0xB2, {'progressive': 10000}],
    'Small Key [Shadow Temple]':                       ['SmallKey', true,  0xB3, {'progressive': 10000}],
    'Small Key [Bottom of the Well]':                  ['SmallKey', true,  0xB4, {'progressive': 10000}],
    'Small Key [Gerudo Training Grounds]':             ['SmallKey',true, 0xB5, {'progressive': 10000}],
    'Small Key [Gerudo Fortress]':                     ['FortressSmallKey',true, 0xB6, {'progressive': 10000}],
    'Small Key [Ganons Castle]':                       ['SmallKey', true,  0xB7, {'progressive': 10000}],
    'Double Defense':                                  ['Item',     true,  0xB8, null],
    'Magic Bean Pack':                                 ['Item',     true,  0xC9, null],
    'Triforce Piece':                                  ['Item',     true,  0xCA, {'progressive': 10000}],
    'Zeldas Letter':                                   ['Item',     true,  0x0B, null],
    'Time Travel':                                     ['Event',    true,  null, null],
    'Scarecrow Song':                                  ['Event',    true,  null, null],
    'Triforce':                                        ['Event',    true,  null, null],

    // Event items otherwise generated by generic event logic
    // can be defined here to enforce their appearance in playthroughs.
    'Water Temple Clear':               ['Event',    true,  null, null],
    'Forest Trial Clear':               ['Event',    true,  null, null],
    'Fire Trial Clear':                 ['Event',    true,  null, null],
    'Water Trial Clear':                ['Event',    true,  null, null],
    'Shadow Trial Clear':               ['Event',    true,  null, null],
    'Spirit Trial Clear':               ['Event',    true,  null, null],
    'Light Trial Clear':                ['Event',    true,  null, null],
    'Epona':                            ['Event',    true,  null, null],

    'Deku Stick Drop':                  ['Drop',     true,  null, null],
    'Deku Nut Drop':                    ['Drop',     true,  null, null],
    'Blue Fire':                        ['Drop',     true,  null, null],
    'Fairy':                            ['Drop',     true,  null, null],
    'Fish':                             ['Drop',     true,  null, null],
    'Bugs':                             ['Drop',     true,  null, null],
    'Big Poe':                          ['Drop',     true,  null, null],
    'Bombchu Drop':                     ['Drop',     true,  null, null],

    // Consumable refills defined mostly to placate 'starting with' options
    'Arrows':                           ['Refill',   null,  null, null],
    'Bombs':                            ['Refill',   null,  null, null],
    'Deku Seeds':                       ['Refill',   null,  null, null],
    'Deku Sticks':                      ['Refill',   null,  null, null],
    'Deku Nuts':                        ['Refill',   null,  null, null],
    'Rupees':                           ['Refill',   null,  null, null],

    'Minuet of Forest':                 ['Song',     true,  0xBB,
                                            {
                                                'text_id': 0x73,
                                                'song_id': 0x02,
                                                'item_id': 0x5A,
                                            }],
    'Bolero of Fire':                   ['Song',     true,  0xBC,
                                            {
                                                'text_id': 0x74,
                                                'song_id': 0x03,
                                                'item_id': 0x5B,
                                            }],
    'Serenade of Water':                ['Song',     true,  0xBD,
                                            {
                                                'text_id': 0x75,
                                                'song_id': 0x04,
                                                'item_id': 0x5C,
                                            }],
    'Requiem of Spirit':                ['Song',     true,  0xBE,
                                            {
                                                'text_id': 0x76,
                                                'song_id': 0x05,
                                                'item_id': 0x5D,
                                            }],
    'Nocturne of Shadow':               ['Song',     true,  0xBF,
                                            {
                                                'text_id': 0x77,
                                                'song_id': 0x06,
                                                'item_id': 0x5E,
                                            }],
    'Prelude of Light':                 ['Song',     true,  0xC0,
                                            {
                                                'text_id': 0x78,
                                                'song_id': 0x07,
                                                'item_id': 0x5F,
                                            }],
    'Zeldas Lullaby':                   ['Song',     true,  0xC1,
                                            {
                                                'text_id': 0xD4,
                                                'song_id': 0x0A,
                                                'item_id': 0x60,
                                            }],
    'Eponas Song':                      ['Song',     true,  0xC2,
                                            {
                                                'text_id': 0xD2,
                                                'song_id': 0x09,
                                                'item_id': 0x61,
                                            }],
    'Sarias Song':                      ['Song',     true,  0xC3,
                                            {
                                                'text_id': 0xD1,
                                                'song_id': 0x08,
                                                'item_id': 0x62,
                                            }],
    'Suns Song':                        ['Song',     true,  0xC4,
                                            {
                                                'text_id': 0xD3,
                                                'song_id': 0x0B,
                                                'item_id': 0x63,
                                            }],
    'Song of Time':                     ['Song',     true,  0xC5,
                                            {
                                                'text_id': 0xD5,
                                                'song_id': 0x0C,
                                                'item_id': 0x64,
                                            }],
    'Song of Storms':                   ['Song',     true,  0xC6,
                                            {
                                                'text_id': 0xD6,
                                                'song_id': 0x0D,
                                                'item_id': 0x65,
                                            }],

    'Buy Deku Nut [5]':                 ['Shop',     true,  0x00, {'object': 0x00BB, 'price': 15}],
    'Buy Arrows [30]':                  ['Shop',     false, 0x01, {'object': 0x00D8, 'price': 60}],
    'Buy Arrows [50]':                  ['Shop',     false, 0x02, {'object': 0x00D8, 'price': 90}],
    'Buy Bombs [5] [25]':               ['Shop',     false, 0x03, {'object': 0x00CE, 'price': 25}],
    'Buy Deku Nut [10]':                ['Shop',     true,  0x04, {'object': 0x00BB, 'price': 30}],
    'Buy Deku Stick [1]':               ['Shop',     true,  0x05, {'object': 0x00C7, 'price': 10}],
    'Buy Bombs [10]':                   ['Shop',     false, 0x06, {'object': 0x00CE, 'price': 50}],
    'Buy Fish':                         ['Shop',     true,  0x07, {'object': 0x00F4, 'price': 200}],
    'Buy Red Potion [30]':              ['Shop',     false, 0x08, {'object': 0x00EB, 'price': 30}],
    'Buy Green Potion':                 ['Shop',     false, 0x09, {'object': 0x00EB, 'price': 30}],
    'Buy Blue Potion':                  ['Shop',     false, 0x0A, {'object': 0x00EB, 'price': 100}],
    'Buy Hylian Shield':                ['Shop',     true,  0x0C, {'object': 0x00DC, 'price': 80}],
    'Buy Deku Shield':                  ['Shop',     true,  0x0D, {'object': 0x00CB, 'price': 40}],
    'Buy Goron Tunic':                  ['Shop',     true,  0x0E, {'object': 0x00F2, 'price': 200}],
    'Buy Zora Tunic':                   ['Shop',     true,  0x0F, {'object': 0x00F2, 'price': 300}],
    'Buy Heart':                        ['Shop',     false, 0x10, {'object': 0x00B7, 'price': 10}],
    'Buy Bombchu [10]':                 ['Shop',     true,  0x15, {'object': 0x00D9, 'price': 99}],
    'Buy Bombchu [20]':                 ['Shop',     true,  0x16, {'object': 0x00D9, 'price': 180}],
    'Buy Bombchu [5]':                  ['Shop',     true,  0x18, {'object': 0x00D9, 'price': 60}],
    'Buy Deku Seeds [30]':              ['Shop',     false, 0x1D, {'object': 0x0119, 'price': 30}],
    'Sold Out':                         ['Shop',     false, 0x26, {'object': 0x0148}],
    'Buy Blue Fire':                    ['Shop',     true,  0x27, {'object': 0x0173, 'price': 300}],
    'Buy Bottle Bug':                   ['Shop',     true,  0x28, {'object': 0x0174, 'price': 50}],
    'Buy Poe':                          ['Shop',     false, 0x2A, {'object': 0x0176, 'price': 30}],
    'Buy Fairy\'s Spirit':              ['Shop',     true,  0x2B, {'object': 0x0177, 'price': 50}],
    'Buy Arrows [10]':                  ['Shop',     false, 0x2C, {'object': 0x00D8, 'price': 20}],
    'Buy Bombs [20]':                   ['Shop',     false, 0x2D, {'object': 0x00CE, 'price': 80}],
    'Buy Bombs [30]':                   ['Shop',     false, 0x2E, {'object': 0x00CE, 'price': 120}],
    'Buy Bombs [5] [35]':               ['Shop',     false, 0x2F, {'object': 0x00CE, 'price': 35}],
    'Buy Red Potion [40]':              ['Shop',     false, 0x30, {'object': 0x00EB, 'price': 40}],
    'Buy Red Potion [50]':              ['Shop',     false, 0x31, {'object': 0x00EB, 'price': 50}],

    'Kokiri Emerald':                   ['DungeonReward',    true,  null,
                                            {
                                                'stone':      true,
                                                'addr2_data': 0x80,
                                                'bit_mask':   0x00040000,
                                                'item_id':    0x6C,
                                                'actor_type': 0x13,
                                                'object_id':  0x00AD,
                                            }],
    'Goron Ruby':                       ['DungeonReward',    true,  null,
                                            {
                                                'stone':      true,
                                                'addr2_data': 0x81,
                                                'bit_mask':   0x00080000,
                                                'item_id':    0x6D,
                                                'actor_type': 0x14,
                                                'object_id':  0x00AD,
                                            }],
    'Zora Sapphire':                    ['DungeonReward',    true,  null,
                                            {
                                                'stone':      true,
                                                'addr2_data': 0x82,
                                                'bit_mask':   0x00100000,
                                                'item_id':    0x6E,
                                                'actor_type': 0x15,
                                                'object_id':  0x00AD,
                                            }],
    'Forest Medallion':                 ['DungeonReward',    true,  null,
                                            {
                                                'medallion':  true,
                                                'addr2_data': 0x3E,
                                                'bit_mask':   0x00000001,
                                                'item_id':    0x66,
                                                'actor_type': 0x0B,
                                                'object_id':  0x00BA,
                                            }],
    'Fire Medallion':                   ['DungeonReward',    true,  null,
                                            {
                                                'medallion':  true,
                                                'addr2_data': 0x3C,
                                                'bit_mask':   0x00000002,
                                                'item_id':    0x67,
                                                'actor_type': 0x09,
                                                'object_id':  0x00BA,
                                            }],
    'Water Medallion':                  ['DungeonReward',    true,  null,
                                            {
                                                'medallion':  true,
                                                'addr2_data': 0x3D,
                                                'bit_mask':   0x00000004,
                                                'item_id':    0x68,
                                                'actor_type': 0x0A,
                                                'object_id':  0x00BA,
                                            }],
    'Spirit Medallion':                 ['DungeonReward',    true,  null,
                                            {
                                                'medallion':  true,
                                                'addr2_data': 0x3F,
                                                'bit_mask':   0x00000008,
                                                'item_id':    0x69,
                                                'actor_type': 0x0C,
                                                'object_id':  0x00BA,
                                            }],
    'Shadow Medallion':                 ['DungeonReward',    true,  null,
                                            {
                                                'medallion':  true,
                                                'addr2_data': 0x41,
                                                'bit_mask':   0x00000010,
                                                'item_id':    0x6A,
                                                'actor_type': 0x0D,
                                                'object_id':  0x00BA,
                                            }],
    'Light Medallion':                  ['DungeonReward',    true,  null,
                                            {
                                                'medallion':  true,
                                                'addr2_data': 0x40,
                                                'bit_mask':   0x00000020,
                                                'item_id':    0x6B,
                                                'actor_type': 0x0E,
                                                'object_id':  0x00BA,
                                            }]
};

module.exports = item_table;