import { GraphBoulder } from "../GraphPlugin.js"
import World from "./World.js"

export const enum BOULDER_TYPE {
    BROWN = 0,
    BRONZE = 1,
    SILVER = 2,
    RED_ICE = 3,
    GOLD = 4,        // This was inserted in 8.2.50 Rob-127, moving HEAVY_BLOCK to 5, but none of the test plandos had any of those shuffled.
    HEAVY_BLOCK = 5, // Probably a good idea to restrict boulder shuffle tracker support to versions after that.
    UNKNOWN = 99,
}

export const BOULDER_TYPE_STRINGS: {[boulder_type: number]: string} = {
    0: 'BOULDER_TYPE.BROWN',
    1: 'BOULDER_TYPE.BRONZE',
    2: 'BOULDER_TYPE.SILVER',
    3: 'BOULDER_TYPE.RED_ICE',
    4: 'BOULDER_TYPE.GOLD',
    5: 'BOULDER_TYPE.HEAVY_BLOCK',
    99: 'BOULDER_TYPE.UNKNOWN',
}

export const BOULDER_TYPE_PLANDO: {[boulder_type: string]: number} = {
    'BOULDER_TYPE.BROWN': BOULDER_TYPE.BROWN,
    'BOULDER_TYPE.BRONZE': BOULDER_TYPE.BRONZE,
    'BOULDER_TYPE.SILVER': BOULDER_TYPE.SILVER,
    'BOULDER_TYPE.RED_ICE': BOULDER_TYPE.RED_ICE,
    'BOULDER_TYPE.HEAVY_BLOCK': BOULDER_TYPE.HEAVY_BLOCK,
    'BOULDER_TYPE.UNKNOWN': BOULDER_TYPE.UNKNOWN,
}

export const boulder_rules: {[boulder_type_name: string]: BOULDER_TYPE} = {
    'BOULDER_TYPE_BROWN': BOULDER_TYPE.BROWN,
    'BOULDER_TYPE_BRONZE': BOULDER_TYPE.BRONZE,
    'BOULDER_TYPE_SILVER': BOULDER_TYPE.SILVER,
    'BOULDER_TYPE_RED_ICE': BOULDER_TYPE.RED_ICE,
    'BOULDER_TYPE_GOLD': BOULDER_TYPE.GOLD,
    'BOULDER_TYPE_HEAVY_BLOCK': BOULDER_TYPE.HEAVY_BLOCK
}

export const vanilla_dungeon_boulders = {
    'Bottom of the Well': {
        'BOTW_CHEST_BOULDER_1': BOULDER_TYPE.BROWN,
        'BOTW_CHEST_BOULDER_2': BOULDER_TYPE.BROWN,
        'BOTW_GRASS_BOULDER_1': BOULDER_TYPE.BROWN,
        'BOTW_GRASS_BOULDER_2': BOULDER_TYPE.BROWN,
    },
    'Ice Cavern': {
        'ICE_CAVERN_UNNAMED_1': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_FREESTANDING_COLLECTIBLE_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_UNNAMED_2': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_TOWARDS_COMPASS_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_TOWARDS_BLOCK_PUSH_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_BLOCK_PUSH_SILVER_RUPEE_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_NEAR_END_BOULDER_1': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_NEAR_END_BOULDER_2': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_NEAR_END_BOULDER_3': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_NEAR_MAP_POT_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_MAP_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_COMPASS_CHEST_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_CAVERN_FREESTANDING_POH_BOULDER': BOULDER_TYPE.RED_ICE,
    },
    'Ganons Castle': {
        'IGC_WATER_TRIAL_BOULDER_1': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_BOULDER_2': BOULDER_TYPE.RED_ICE,
    }
}

export const vanilla_dungeon_boulders_8_1 = {
    'Bottom of the Well': {
        'BOTW_UNNAMED_1': BOULDER_TYPE.BROWN,
        'BOTW_UNNAMED_2': BOULDER_TYPE.BROWN,
    }
}

export const vanilla_dungeon_boulders_8_2 = {
    'Bottom of the Well': {
        'BOTW_BOMB_FLOWER_BOULDER_1': BOULDER_TYPE.BROWN,
        'BOTW_BOMB_FLOWER_BOULDER_2': BOULDER_TYPE.BROWN,
    }
}

export const mq_dungeon_boulders = {
    'Deku Tree':{
        'DEKU_COMPASS_BOULDER_1': BOULDER_TYPE.BROWN,
        'DEKU_COMPASS_BOULDER_2': BOULDER_TYPE.BROWN,
        'DEKU_COMPASS_BOULDER_3': BOULDER_TYPE.BROWN,
    },
    'Dodongos Cavern': {
        'DC_LOBBY_SWITCH_BOULDER': BOULDER_TYPE.BROWN,
        'DC_LOBBY_UNK': BOULDER_TYPE.BROWN,
        'DC_LOBBY_UPPER_BOULDER_1': BOULDER_TYPE.BROWN,
        'DC_LOBBY_UPPER_BOULDER_2': BOULDER_TYPE.BROWN,
        'DC_LOBBY_UPPER_BOULDER_3': BOULDER_TYPE.BROWN,
        'DC_LOWER_HALL_FLOWER_BOULDER': BOULDER_TYPE.BROWN,
        'DC_LOWER_HALL_EYESWITCH_BOULDER': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_1': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_2': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_3': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_4': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_5': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_6': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_7': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_8': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_9': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_10': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_11': BOULDER_TYPE.BROWN,
        'DC_UPPER_LIZALFOS_BOULDER_12': BOULDER_TYPE.BROWN,
        'DC_TWOFLAMES_BOULDER': BOULDER_TYPE.BROWN,
    },
    'Jabu Jabus Belly': {
        'JABU_ENTRANCE_BOULDER': BOULDER_TYPE.BROWN,
        'JABU_PITS_GRASS_BOULDER_1': BOULDER_TYPE.BROWN,
        'JABU_PITS_GRASS_BOULDER_2': BOULDER_TYPE.BROWN,
        'JABU_PITS_WALL_BOULDER_1': BOULDER_TYPE.BROWN,
        'JABU_PITS_WALL_BOULDER_2': BOULDER_TYPE.BROWN,
        'JABU_PITS_WALL_BOULDER_3': BOULDER_TYPE.BROWN,
        'JABU_DEPTHS_BOULDER_1': BOULDER_TYPE.BROWN,
        'JABU_DEPTHS_BOULDER_2': BOULDER_TYPE.BROWN,
        'JABU_TAILS_BOULDER_WALL': BOULDER_TYPE.BROWN,
        'JABU_TAILS_BOULDER_FLOOR': BOULDER_TYPE.BROWN,
    },
    'Spirit Temple': {
        'SPIRIT_LOBBY_BOULDER_LOWER_LEFT': BOULDER_TYPE.BROWN,
        'SPIRIT_LOBBY_CEILING_BOULDER': BOULDER_TYPE.BROWN,
        'SPIRIT_LOBBY_EYESWITCH_BOULDER': BOULDER_TYPE.BROWN,
        'SPIRIT_LOBBY_BOULDER_LOWER_RIGHT': BOULDER_TYPE.BROWN,
        'SPIRIT_EARLY_ADULT_BOULDER': BOULDER_TYPE.BROWN,
        'SPIRIT_CHILD_CRAWLSPACE_BOULDER': BOULDER_TYPE.BROWN,
        'SPIRIT_CHILD_GATE_EYESWITCH_BOULDER': BOULDER_TYPE.BROWN,
        'SPIRIT_CHILD_GATE_WALL_BOULDER_1': BOULDER_TYPE.BROWN,
        'SPIRIT_CHILD_GATE_WALL_BOULDER_2': BOULDER_TYPE.BROWN,
    },
    'Bottom of the Well': {
        'BOTW_LEFT_SIDE_BOULDER_1': BOULDER_TYPE.BROWN,
        'BOTW_LEFT_SIDE_BOULDER_2': BOULDER_TYPE.BROWN,
        'BOTW_EYESWITCH_WALL_BOULDER': BOULDER_TYPE.BROWN,
    },
    'Ice Cavern': {
        'ICE_TOWARDS_LARGE_ROOM_BOULDER_1': BOULDER_TYPE.RED_ICE,
        'ICE_TOWARDS_LARGE_ROOM_BOULDER_2': BOULDER_TYPE.RED_ICE,
        'ICE_TOWARDS_LARGE_ROOM_BOULDER_3': BOULDER_TYPE.RED_ICE,
        'ICE_TOWARDS_COMPASS_BOULDER_1': BOULDER_TYPE.RED_ICE,
        'ICE_TOWARDS_COMPASS_BOULDER_2': BOULDER_TYPE.RED_ICE,
        'ICE_TOWARDS_COMPASS_BOULDER_3': BOULDER_TYPE.RED_ICE,
        'ICE_LARGE_ROOM_BOULDER_1': BOULDER_TYPE.RED_ICE,
        'ICE_LARGE_ROOM_BOULDER_2': BOULDER_TYPE.RED_ICE,
        'ICE_LARGE_ROOM_BOULDER_3': BOULDER_TYPE.RED_ICE,
        'ICE_COMPASS_SKULLTULA_BOULDER': BOULDER_TYPE.RED_ICE,
        'ICE_MAP_BOULDER': BOULDER_TYPE.RED_ICE,
    },
    'Gerudo Training Ground': {
        'GTG_STALFOS_ROOM_BOULDER': BOULDER_TYPE.RED_ICE,
    },
    'Ganons Castle': {
        'IGC_WATER_TRIAL_CHEST_BOULDER': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_RECOVERYHEART_BOULDER': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_UNK_1': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_FIRST_ROOM_DOOR_BOULDER_1': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_FIRST_ROOM_DOOR_BOULDER_2': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_FIRST_ROOM_DOOR_BOULDER_3': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_FIRST_ROOM_DOOR_BOULDER_4': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_SILVER_RUPEE_BOULDER': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_ENDING_BOULDER_1': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_ENDING_BOULDER_2': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_ENDING_BOULDER_3': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_ENDING_BOULDER_4': BOULDER_TYPE.RED_ICE,
        'IGC_WATER_TRIAL_ENDING_BOULDER_5': BOULDER_TYPE.RED_ICE,
    }
}

export const boulder_list = {
    'HF_UNNAMED_1': BOULDER_TYPE.SILVER,
    'HF_SOUTHEAST_GROTTO_BOULDER': BOULDER_TYPE.BROWN,
    'HF_NEAR_MARKET_GROTTO_BOULDER': BOULDER_TYPE.BROWN,
    'HF_FAIRY_GROTTO_BOULDER': BOULDER_TYPE.BROWN,
    'HF_COW_GROTTO_ADULT_BOULDER': BOULDER_TYPE.BRONZE,
    'HF_UNNAMED_2': BOULDER_TYPE.BRONZE,
    'HF_UNNAMED_3': BOULDER_TYPE.BRONZE,
    'HF_UNNAMED_4': BOULDER_TYPE.BRONZE,
    'HF_UNNAMED_5': BOULDER_TYPE.SILVER,
    'ZR_CHILD_ENTRY_BOULDER_1': BOULDER_TYPE.BROWN,
    'ZR_CHILD_ENTRY_BOULDER_2': BOULDER_TYPE.BROWN,
    'ZR_CHILD_ENTRY_BOULDER_3': BOULDER_TYPE.BROWN,
    'ZR_FAIRY_GROTTO_BOULDER': BOULDER_TYPE.BROWN,
    'HF_UNNAMED_6': BOULDER_TYPE.BROWN,
    'ZD_ADULT_SHOP_BOULDER': BOULDER_TYPE.RED_ICE,
    'ZD_KING_ZORA_BOULDER': BOULDER_TYPE.RED_ICE,
    'ZF_SECRET_SILVER_BOULDER': BOULDER_TYPE.SILVER,
    'ZF_UNNAMED_1': BOULDER_TYPE.BROWN,
    'ZF_SECRET_BROWN_BOULDER': BOULDER_TYPE.BROWN,
    'GV_CHEST_BOULDER_1': BOULDER_TYPE.BRONZE,
    'GV_UNNAMED_2': BOULDER_TYPE.BRONZE,
    'GV_UNNAMED_3': BOULDER_TYPE.BRONZE,
    'GV_UNNAMED_4': BOULDER_TYPE.BRONZE,
    'GV_UNNAMED_5': BOULDER_TYPE.BRONZE,
    'GV_CHEST_BOULDER_2': BOULDER_TYPE.BRONZE,
    'GV_CHEST_BOULDER_3': BOULDER_TYPE.BRONZE,
    'GV_CHEST_BOULDER_4': BOULDER_TYPE.BRONZE,
    'GV_UNNAMED_9': BOULDER_TYPE.BROWN,
    'GV_UNNAMED_10': BOULDER_TYPE.BROWN,
    'GV_UNNAMED_11': BOULDER_TYPE.BROWN,
    'GV_OCTOROK_GROTTO_BOULDER': BOULDER_TYPE.SILVER,
    'LW_NEAR_SHORTCUT_BOULDER': BOULDER_TYPE.BROWN,
    'LW_RUPEE_BOULDER': BOULDER_TYPE.BROWN,
    'LW_SCRUBS_GROTTO_BOULDER': BOULDER_TYPE.BROWN,
    'COLOSSUS_GROTTO_BOULDER': BOULDER_TYPE.SILVER,
    'HC_CHILD_FAIRY_BOULDER': BOULDER_TYPE.BROWN,
    'DMT_ADULT_GC_SKULLTULA_BOULDER': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_1': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_2': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_3': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_4': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_5': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_6': BOULDER_TYPE.BRONZE,
    'DMT_ADULT_SUMMIT_SKULLTULA_BOULDER': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_7': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_8': BOULDER_TYPE.BRONZE,
    'DMT_UNNAMED_9': BOULDER_TYPE.BRONZE,
    'DMT_CHILD_LOWER_BOULDER': BOULDER_TYPE.BROWN,
    'DMT_MIDDLE_BOULDER': BOULDER_TYPE.BROWN,
    'DMT_UPPER_BOULDER': BOULDER_TYPE.BROWN,
    'DMT_COW_GROTTO_BOULDER': BOULDER_TYPE.BROWN,
    'DMC_UNNAMED_1': BOULDER_TYPE.BROWN,
    'DMC_UNNAMED_2': BOULDER_TYPE.BROWN,
    'DMC_SCRUB_GROTTO_BOULDER': BOULDER_TYPE.BRONZE,
    'DMC_FAIRY_BOULDER_1': BOULDER_TYPE.BRONZE,
    'DMC_FAIRY_BOULDER_2': BOULDER_TYPE.BRONZE,
    'DMC_BOULDER_NEAR_FAIRY': BOULDER_TYPE.BRONZE,
    'DMC_CHILD_FIRE_TEMPLE_BOULDER_1': BOULDER_TYPE.SILVER,
    'DMC_CHILD_FIRE_TEMPLE_BOULDER_2': BOULDER_TYPE.SILVER,
    'DMC_CHILD_FIRE_TEMPLE_BOULDER_3': BOULDER_TYPE.SILVER,
    'DMC_UPPER_GROTTO_BOULDER': BOULDER_TYPE.BROWN,
    'DMC_UNNAMED_3': BOULDER_TYPE.BROWN,
    'DMC_UNNAMED_4': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_1': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_2': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_3': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_4': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_5': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_6': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_7': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_8': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_9': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_10': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_11': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_12': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_13': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_14': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_15': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_16': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_17': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_18': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_19': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_20': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_21': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_22': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_23': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_24': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_25': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_26': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_27': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_28': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_29': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_30': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_31': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_32': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_33': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_34': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_35': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_36': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_37': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_38': BOULDER_TYPE.BROWN,
    'GC_BOULDER_MAZE_39': BOULDER_TYPE.BRONZE,
    'GC_BOULDER_MAZE_40': BOULDER_TYPE.BRONZE,
    'GC_BOULDER_MAZE_41': BOULDER_TYPE.BRONZE,
    'GC_BOULDER_MAZE_42': BOULDER_TYPE.SILVER,
    'GC_BOULDER_MAZE_43': BOULDER_TYPE.BRONZE,
    'GC_BOULDER_MAZE_44': BOULDER_TYPE.BRONZE,
    'GC_UPPER_BOULDER_1': BOULDER_TYPE.BROWN,
    'GC_UPPER_BOULDER_2': BOULDER_TYPE.BROWN,
    'GC_UPPER_BOULDER_3': BOULDER_TYPE.BROWN,
    'GC_LW_BOULDER_1': BOULDER_TYPE.BROWN,
    'GC_LW_BOULDER_2': BOULDER_TYPE.BROWN,
    'GC_LW_BOULDER_3': BOULDER_TYPE.BROWN,
    'OGC_UNNAMED_1': BOULDER_TYPE.BRONZE,
    'OGC_UNNAMED_2': BOULDER_TYPE.BRONZE,
    'OGC_UNNAMED_3': BOULDER_TYPE.BRONZE,
    'OGC_UNNAMED_4': BOULDER_TYPE.SILVER,
    'OGC_UNNAMED_5': BOULDER_TYPE.SILVER,
    'OGC_UNNAMED_6': BOULDER_TYPE.SILVER,
    'OGC_UNNAMED_7': BOULDER_TYPE.SILVER,
}

export class Boulder implements GraphBoulder {
    public original_type: BOULDER_TYPE;
    public checked: boolean = false;
    public alias: string = '';
    public shuffled: boolean = false;
    public user_type: BOULDER_TYPE | null = null;
    public hinted = false;

    constructor(
        public name: string,
        public type: BOULDER_TYPE,
        public world: World,
    ) {
        this.alias = this.name;
        this.original_type = this.type;
    }
}