type EntranceConnectionData = [entrance_name: string, entrance_data: object];
type EntranceTableEntry = [entrance_type: string, forward_entry: EntranceConnectionData, reverse_entry?: EntranceConnectionData];

const entrance_shuffle_table: EntranceTableEntry[] = [
    ['Dungeon',         ['KF Outside Deku Tree -> Deku Tree Lobby',                         { 'index': 0x0000 }],
                        ['Deku Tree Lobby -> KF Outside Deku Tree',                         { 'index': 0x0209 }]],
    ['Dungeon',         ['Death Mountain -> Dodongos Cavern Beginning',                     { 'index': 0x0004 }],
                        ['Dodongos Cavern Beginning -> Death Mountain',                     { 'index': 0x0242 }]],
    ['Dungeon',         ['Zoras Fountain -> Jabu Jabus Belly Beginning',                    { 'index': 0x0028 }],
                        ['Jabu Jabus Belly Beginning -> Zoras Fountain',                    { 'index': 0x0221 }]],
    ['Dungeon',         ['SFM Forest Temple Entrance Ledge -> Forest Temple Lobby',         { 'index': 0x0169 }],
                        ['Forest Temple Lobby -> SFM Forest Temple Entrance Ledge',         { 'index': 0x0215 }]],
    ['Dungeon',         ['DMC Fire Temple Entrance -> Fire Temple Lower',                   { 'index': 0x0165 }],
                        ['Fire Temple Lower -> DMC Fire Temple Entrance',                   { 'index': 0x024A }]],
    ['Dungeon',         ['Lake Hylia -> Water Temple Lobby',                                { 'index': 0x0010 }],
                        ['Water Temple Lobby -> Lake Hylia',                                { 'index': 0x021D }]],
    ['Dungeon',         ['Graveyard Warp Pad Region -> Shadow Temple Entryway',             { 'index': 0x0037 }],
                        ['Shadow Temple Entryway -> Graveyard Warp Pad Region',             { 'index': 0x0205 }]],
    ['Dungeon',         ['Desert Colossus -> Spirit Temple Lobby',                          { 'index': 0x0082 }],
                        ['Spirit Temple Lobby -> Desert Colossus From Spirit Lobby',        { 'index': 0x01E1 }]],
    ['Dungeon',         ['Kakariko Village -> Bottom of the Well',                          { 'index': 0x0098 }],
                        ['Bottom of the Well -> Kakariko Village',                          { 'index': 0x02A6 }]],
    ['Dungeon',         ['ZF Ice Ledge -> Ice Cavern Beginning',                            { 'index': 0x0088 }],
                        ['Ice Cavern Beginning -> ZF Ice Ledge',                            { 'index': 0x03D4 }]],
    ['Dungeon',         ['Gerudo Fortress -> Gerudo Training Ground Lobby',                 { 'index': 0x0008 }],
                        ['Gerudo Training Ground Lobby -> Gerudo Fortress',                 { 'index': 0x03A8 }]],

    ['DungeonSpecial',  ['Ganons Castle Grounds -> Ganons Castle Lobby',                    { 'index': 0x0467 }],
                        ['Ganons Castle Lobby -> Castle Grounds From Ganons Castle',        { 'index': 0x023D }]],

    ['ChildBoss',       ['Deku Tree Before Boss -> Queen Gohma Boss Room',                  { 'index': 0x040f, 'savewarp_addresses': [ 0xB06292, 0xBC6162, 0xBC60AE ] }],
                        ['Queen Gohma Boss Room -> Deku Tree Before Boss',                  { 'index': 0x0252 }]],
    ['ChildBoss',       ['Dodongos Cavern Before Boss -> King Dodongo Boss Room',           { 'index': 0x040b, 'savewarp_addresses': [ 0xB062B6, 0xBC616E ] }],
                        ['King Dodongo Boss Room -> Dodongos Cavern Mouth',                 { 'index': 0x00c5 }]],
    ['ChildBoss',       ['Jabu Jabus Belly Before Boss -> Barinade Boss Room',              { 'index': 0x0301, 'savewarp_addresses': [ 0xB062C2, 0xBC60C2 ] }],
                        ['Barinade Boss Room -> Jabu Jabus Belly Before Boss',              { 'index': 0x0407 }]],
    ['AdultBoss',       ['Forest Temple Before Boss -> Phantom Ganon Boss Room',            { 'index': 0x000c, 'savewarp_addresses': [ 0xB062CE, 0xBC6182 ] }],
                        ['Phantom Ganon Boss Room -> Forest Temple Before Boss',            { 'index': 0x024E }]],
    ['AdultBoss',       ['Fire Temple Before Boss -> Volvagia Boss Room',                   { 'index': 0x0305, 'savewarp_addresses': [ 0xB062DA, 0xBC60CE ] }],
                        ['Volvagia Boss Room -> Fire Temple Before Boss',                   { 'index': 0x0175 }]],
    ['AdultBoss',       ['Water Temple Before Boss -> Morpha Boss Room',                    { 'index': 0x0417, 'savewarp_addresses': [ 0xB062E6, 0xBC6196 ] }],
                        ['Morpha Boss Room -> Water Temple Before Boss',                    { 'index': 0x0423 }]],
    ['AdultBoss',       ['Shadow Temple Before Boss -> Bongo Bongo Boss Room',              { 'index': 0x0413, 'savewarp_addresses': [ 0xB062FE, 0xBC61AA ] }],
                        ['Bongo Bongo Boss Room -> Shadow Temple Before Boss',              { 'index': 0x02B2 }]],
    ['AdultBoss',       ['Spirit Temple Before Boss -> Twinrova Boss Room',                 { 'index': 0x008D, 'savewarp_addresses': [ 0xB062F2, 0xBC6122 ] }],
                        ['Twinrova Boss Room -> Spirit Temple Before Boss',                 { 'index': 0x02F5 }]],

    ['Interior',        ['Kokiri Forest -> KF Midos House',                                 { 'index': 0x0433 }],
                        ['KF Midos House -> Kokiri Forest',                                 { 'index': 0x0443 }]],
    ['Interior',        ['Kokiri Forest -> KF Sarias House',                                { 'index': 0x0437 }],
                        ['KF Sarias House -> Kokiri Forest',                                { 'index': 0x0447 }]],
    ['Interior',        ['Kokiri Forest -> KF House of Twins',                              { 'index': 0x009C }],
                        ['KF House of Twins -> Kokiri Forest',                              { 'index': 0x033C }]],
    ['Interior',        ['Kokiri Forest -> KF Know It All House',                           { 'index': 0x00C9 }],
                        ['KF Know It All House -> Kokiri Forest',                           { 'index': 0x026A }]],
    ['Interior',        ['Kokiri Forest -> KF Kokiri Shop',                                 { 'index': 0x00C1 }],
                        ['KF Kokiri Shop -> Kokiri Forest',                                 { 'index': 0x0266 }]],
    ['Interior',        ['Lake Hylia -> LH Lab',                                            { 'index': 0x0043 }],
                        ['LH Lab -> Lake Hylia',                                            { 'index': 0x03CC }]],
    ['Interior',        ['LH Fishing Island -> LH Fishing Hole',                            { 'index': 0x045F }],
                        ['LH Fishing Hole -> LH Fishing Island',                            { 'index': 0x0309 }]],
    ['Interior',        ['GV Fortress Side -> GV Carpenter Tent',                           { 'index': 0x03A0 }],
                        ['GV Carpenter Tent -> GV Fortress Side',                           { 'index': 0x03D0 }]],
    ['Interior',        ['Market Entrance -> Market Guard House',                           { 'index': 0x007E }],
                        ['Market Guard House -> Market Entrance',                           { 'index': 0x026E }]],
    ['Interior',        ['Market -> Market Mask Shop',                                      { 'index': 0x0530 }],
                        ['Market Mask Shop -> Market',                                      { 'index': 0x01D1, 'addresses': [0xC6DA5E] }]],
    ['Interior',        ['Market -> Market Bombchu Bowling',                                { 'index': 0x0507 }],
                        ['Market Bombchu Bowling -> Market',                                { 'index': 0x03BC }]],
    ['Interior',        ['Market -> Market Potion Shop',                                    { 'index': 0x0388 }],
                        ['Market Potion Shop -> Market',                                    { 'index': 0x02A2 }]],
    ['Interior',        ['Market -> Market Treasure Chest Game',                            { 'index': 0x0063 }],
                        ['Market Treasure Chest Game -> Market',                            { 'index': 0x01D5 }]],
    ['Interior',        ['Market Back Alley -> Market Bombchu Shop',                        { 'index': 0x0528 }],
                        ['Market Bombchu Shop -> Market Back Alley',                        { 'index': 0x03C0 }]],
    ['Interior',        ['Market Back Alley -> Market Man in Green House',                  { 'index': 0x043B }],
                        ['Market Man in Green House -> Market Back Alley',                  { 'index': 0x0067 }]],
    ['Interior',        ['Kakariko Village -> Kak Carpenter Boss House',                    { 'index': 0x02FD }],
                        ['Kak Carpenter Boss House -> Kakariko Village',                    { 'index': 0x0349 }]],
    ['Interior',        ['Kakariko Village -> Kak House of Skulltula',                      { 'index': 0x0550 }],
                        ['Kak House of Skulltula -> Kakariko Village',                      { 'index': 0x04EE }]],
    ['Interior',        ['Kakariko Village -> Kak Impas House',                             { 'index': 0x039C }],
                        ['Kak Impas House -> Kakariko Village',                             { 'index': 0x0345 }]],
    ['Interior',        ['Kak Impas Ledge -> Kak Impas House Back',                         { 'index': 0x05C8 }],
                        ['Kak Impas House Back -> Kak Impas Ledge',                         { 'index': 0x05DC }]],
    ['Interior',        ['Kak Backyard -> Kak Odd Medicine Building',                       { 'index': 0x0072 }],
                        ['Kak Odd Medicine Building -> Kak Backyard',                       { 'index': 0x034D }]],
    ['Interior',        ['Graveyard -> Graveyard Dampes House',                             { 'index': 0x030D }],
                        ['Graveyard Dampes House -> Graveyard',                             { 'index': 0x0355 }]],
    ['Interior',        ['Goron City -> GC Shop',                                           { 'index': 0x037C }],
                        ['GC Shop -> Goron City',                                           { 'index': 0x03FC }]],
    ['Interior',        ['Zoras Domain -> ZD Shop',                                         { 'index': 0x0380 }],
                        ['ZD Shop -> Zoras Domain',                                         { 'index': 0x03C4 }]],
    ['Interior',        ['Lon Lon Ranch -> LLR Talons House',                               { 'index': 0x004F }],
                        ['LLR Talons House -> Lon Lon Ranch',                               { 'index': 0x0378 }]],
    ['Interior',        ['Lon Lon Ranch -> LLR Stables',                                    { 'index': 0x02F9 }],
                        ['LLR Stables -> Lon Lon Ranch',                                    { 'index': 0x042F }]],
    ['Interior',        ['Lon Lon Ranch -> LLR Tower',                                      { 'index': 0x05D0 }],
                        ['LLR Tower -> Lon Lon Ranch',                                      { 'index': 0x05D4 }]],
    ['Interior',        ['Market -> Market Bazaar',                                         { 'index': 0x052C }],
                        ['Market Bazaar -> Market',                                         { 'index': 0x03B8, 'addresses': [0xBEFD74] }]],
    ['Interior',        ['Market -> Market Shooting Gallery',                               { 'index': 0x016D }],
                        ['Market Shooting Gallery -> Market',                               { 'index': 0x01CD, 'addresses': [0xBEFD7C] }]],
    ['Interior',        ['Kakariko Village -> Kak Bazaar',                                  { 'index': 0x00B7 }],
                        ['Kak Bazaar -> Kakariko Village',                                  { 'index': 0x0201, 'addresses': [0xBEFD72] }]],
    ['Interior',        ['Kakariko Village -> Kak Shooting Gallery',                        { 'index': 0x003B }],
                        ['Kak Shooting Gallery -> Kakariko Village',                        { 'index': 0x0463, 'addresses': [0xBEFD7A] }]],
    ['Interior',        ['Desert Colossus -> Colossus Great Fairy Fountain',                { 'index': 0x0588 }],
                        ['Colossus Great Fairy Fountain -> Desert Colossus',                { 'index': 0x057C, 'addresses': [0xBEFD82] }]],
    ['Interior',        ['Hyrule Castle Grounds -> HC Great Fairy Fountain',                { 'index': 0x0578 }],
                        ['HC Great Fairy Fountain -> Castle Grounds',                       { 'index': 0x0340, 'addresses': [0xBEFD80] }]],
    ['Interior',        ['Ganons Castle Grounds -> OGC Great Fairy Fountain',               { 'index': 0x04C2 }],
                        ['OGC Great Fairy Fountain -> Castle Grounds',                      { 'index': 0x0340, 'addresses': [0xBEFD6C] }]],
    ['Interior',        ['DMC Lower Nearby -> DMC Great Fairy Fountain',                    { 'index': 0x04BE }],
                        ['DMC Great Fairy Fountain -> DMC Lower Local',                     { 'index': 0x0482, 'addresses': [0xBEFD6A] }]],
    ['Interior',        ['Death Mountain Summit -> DMT Great Fairy Fountain',               { 'index': 0x0315 }],
                        ['DMT Great Fairy Fountain -> Death Mountain Summit',               { 'index': 0x045B, 'addresses': [0xBEFD68] }]],
    ['Interior',        ['Zoras Fountain -> ZF Great Fairy Fountain',                       { 'index': 0x0371 }],
                        ['ZF Great Fairy Fountain -> Zoras Fountain',                       { 'index': 0x0394, 'addresses': [0xBEFD7E] }]],

    ['SpecialInterior', ['Kokiri Forest -> KF Links House',                                 { 'index': 0x0272 }],
                        ['KF Links House -> Kokiri Forest',                                 { 'index': 0x0211 }]],
    ['SpecialInterior', ['ToT Entrance -> Temple of Time',                                  { 'index': 0x0053 }],
                        ['Temple of Time -> ToT Entrance',                                  { 'index': 0x0472 }]],
    ['SpecialInterior', ['Kakariko Village -> Kak Windmill',                                { 'index': 0x0453 }],
                        ['Kak Windmill -> Kakariko Village',                                { 'index': 0x0351 }]],
    ['SpecialInterior', ['Kakariko Village -> Kak Potion Shop Front',                       { 'index': 0x0384 }],
                        ['Kak Potion Shop Front -> Kakariko Village',                       { 'index': 0x044B }]],
    ['SpecialInterior', ['Kak Backyard -> Kak Potion Shop Back',                            { 'index': 0x03EC }],
                        ['Kak Potion Shop Back -> Kak Backyard',                            { 'index': 0x04FF }]],

    ['Hideout',         ['Gerudo Fortress -> Hideout 1 Torch Jail',                         { 'index': 0x0486 }],
                        ['Hideout 1 Torch Jail -> Gerudo Fortress',                         { 'index': 0x0231 }]],
    ['Hideout',         ['GF Entrances Behind Crates -> Hideout 1 Torch Jail',              { 'index': 0x048A }],
                        ['Hideout 1 Torch Jail -> GF Entrances Behind Crates',              { 'index': 0x0235 }]],
    ['Hideout',         ['GF Entrances Behind Crates -> Hideout Kitchen Hallway',           { 'index': 0x048E }],
                        ['Hideout Kitchen Hallway -> GF Entrances Behind Crates',           { 'index': 0x0239 }]],
    ['Hideout',         ['Gerudo Fortress -> Hideout Kitchen Hallway',                      { 'index': 0x0492 }],
                        ['Hideout Kitchen Hallway -> Gerudo Fortress',                      { 'index': 0x02AA }]],
    ['Hideout',         ['Gerudo Fortress -> Hideout 4 Torches Jail',                       { 'index': 0x0496 }],
                        ['Hideout 4 Torches Jail -> Gerudo Fortress',                       { 'index': 0x02BA }]],
    ['Hideout',         ['GF Roof Entrance Cluster -> Hideout 4 Torches Jail',              { 'index': 0x049A }],
                        ['Hideout 4 Torches Jail -> GF Roof Entrance Cluster',              { 'index': 0x02BE }]],
    ['Hideout',         ['Gerudo Fortress -> Hideout 2 Torches Jail',                       { 'index': 0x049E }],
                        ['Hideout 2 Torches Jail -> Gerudo Fortress',                       { 'index': 0x02C2 }]],
    ['Hideout',         ['GF Roof Entrance Cluster -> Hideout 2 Torches Jail',              { 'index': 0x04A2 }],
                        ['Hideout 2 Torches Jail -> GF Roof Entrance Cluster',              { 'index': 0x02C6 }]],
    ['Hideout',         ['GF Roof Entrance Cluster -> Hideout Kitchen Front',               { 'index': 0x04A6 }],
                        ['Hideout Kitchen Front -> GF Roof Entrance Cluster',               { 'index': 0x02D2 }]],
    ['Hideout',         ['GF Kitchen Roof Access -> Hideout Kitchen Rear',                  { 'index': 0x04AA }],
                        ['Hideout Kitchen Rear -> GF Kitchen Roof Access',                  { 'index': 0x02D6 }]],
    ['Hideout',         ['GF Break Room Entrance -> Hideout Break Room',                    { 'index': 0x04AE }],
                        ['Hideout Break Room -> GF Break Room Entrance',                    { 'index': 0x02DA }]],
    ['Hideout',         ['GF Balcony -> Hideout Hall to Balcony',                           { 'index': 0x04B2 }],
                        ['Hideout Hall to Balcony -> GF Balcony',                           { 'index': 0x02DE }]],
    ['Hideout',         ['GF 3 Torches Jail Exterior -> Hideout 3 Torches Jail',            { 'index': 0x0570 }],
                        ['Hideout 3 Torches Jail -> GF 3 Torches Jail Exterior',            { 'index': 0x03A4 }]],

    ['Grotto',          ['Desert Colossus -> Colossus Grotto',                              { 'grotto_id': 0x00, 'entrance': 0x05BC, 'content': 0xFD, 'scene': 0x5C }],
                        ['Colossus Grotto -> Desert Colossus',                              { 'grotto_id': 0x00, 'savewarp_fallback': 0x01F1 }]],
    ['Grotto',          ['Lake Hylia -> LH Grotto',                                         { 'grotto_id': 0x01, 'entrance': 0x05A4, 'content': 0xEF, 'scene': 0x57 }],
                        ['LH Grotto -> Lake Hylia',                                         { 'grotto_id': 0x01, 'savewarp_fallback': 0x0604 }]],
    ['Grotto',          ['Zora River -> ZR Storms Grotto',                                  { 'grotto_id': 0x02, 'entrance': 0x05BC, 'content': 0xEB, 'scene': 0x54 }],
                        ['ZR Storms Grotto -> Zora River',                                  { 'grotto_id': 0x02, 'savewarp_fallback': 0x0199 }]],
    ['Grotto',          ['Zora River -> ZR Fairy Grotto',                                   { 'grotto_id': 0x03, 'entrance': 0x036D, 'content': 0xE6, 'scene': 0x54 }],
                        ['ZR Fairy Grotto -> Zora River',                                   { 'grotto_id': 0x03, 'savewarp_fallback': 0x0199 }]],
    ['Grotto',          ['Zora River -> ZR Open Grotto',                                    { 'grotto_id': 0x04, 'entrance': 0x003F, 'content': 0x29, 'scene': 0x54 }],
                        ['ZR Open Grotto -> Zora River',                                    { 'grotto_id': 0x04, 'savewarp_fallback': 0x0199 }]],
    ['Grotto',          ['DMC Lower Nearby -> DMC Hammer Grotto',                           { 'grotto_id': 0x05, 'entrance': 0x05A4, 'content': 0xF9, 'scene': 0x61 }],
                        ['DMC Hammer Grotto -> DMC Lower Local',                            { 'grotto_id': 0x05, 'savewarp_fallback': 0x0246 }]],
    ['Grotto',          ['DMC Upper Nearby -> DMC Upper Grotto',                            { 'grotto_id': 0x06, 'entrance': 0x003F, 'content': 0x7A, 'scene': 0x61 }],
                        ['DMC Upper Grotto -> DMC Upper Local',                             { 'grotto_id': 0x06, 'savewarp_fallback': 0x0147 }]],
    ['Grotto',          ['GC Grotto Platform -> GC Grotto',                                 { 'grotto_id': 0x07, 'entrance': 0x05A4, 'content': 0xFB, 'scene': 0x62 }],
                        ['GC Grotto -> GC Grotto Platform',                                 { 'grotto_id': 0x07, 'savewarp_fallback': 0x014D }]],
    ['Grotto',          ['Death Mountain -> DMT Storms Grotto',                             { 'grotto_id': 0x08, 'entrance': 0x003F, 'content': 0x57, 'scene': 0x60 }],
                        ['DMT Storms Grotto -> Death Mountain',                             { 'grotto_id': 0x08, 'savewarp_fallback': 0x01B9 }]],
    ['Grotto',          ['Death Mountain Summit -> DMT Cow Grotto',                         { 'grotto_id': 0x09, 'entrance': 0x05FC, 'content': 0xF8, 'scene': 0x60 }],
                        ['DMT Cow Grotto -> Death Mountain Summit',                         { 'grotto_id': 0x09, 'savewarp_fallback': 0x045B }]],
    ['Grotto',          ['Kak Backyard -> Kak Open Grotto',                                 { 'grotto_id': 0x0A, 'entrance': 0x003F, 'content': 0x28, 'scene': 0x52 }],
                        ['Kak Open Grotto -> Kak Backyard',                                 { 'grotto_id': 0x0A, 'savewarp_fallback': 0x04FF }]],
    ['Grotto',          ['Kakariko Village -> Kak Redead Grotto',                           { 'grotto_id': 0x0B, 'entrance': 0x05A0, 'content': 0xE7, 'scene': 0x52 }],
                        ['Kak Redead Grotto -> Kakariko Village',                           { 'grotto_id': 0x0B, 'savewarp_fallback': 0x0349 }]],
    ['Grotto',          ['Hyrule Castle Grounds -> HC Storms Grotto',                       { 'grotto_id': 0x0C, 'entrance': 0x05B8, 'content': 0xF6, 'scene': 0x5F }],
                        ['HC Storms Grotto -> Castle Grounds',                              { 'grotto_id': 0x0C, 'savewarp_fallback': 0x0340 }]],
    ['Grotto',          ['Hyrule Field -> HF Tektite Grotto',                               { 'grotto_id': 0x0D, 'entrance': 0x05C0, 'content': 0xE1, 'scene': 0x51 }],
                        ['HF Tektite Grotto -> Hyrule Field',                               { 'grotto_id': 0x0D, 'savewarp_fallback': 0x01F9 }]],
    ['Grotto',          ['Hyrule Field -> HF Near Kak Grotto',                              { 'grotto_id': 0x0E, 'entrance': 0x0598, 'content': 0xE5, 'scene': 0x51 }],
                        ['HF Near Kak Grotto -> Hyrule Field',                              { 'grotto_id': 0x0E, 'savewarp_fallback': 0x017D }]],
    ['Grotto',          ['Hyrule Field -> HF Fairy Grotto',                                 { 'grotto_id': 0x0F, 'entrance': 0x036D, 'content': 0xFF, 'scene': 0x51 }],
                        ['HF Fairy Grotto -> Hyrule Field',                                 { 'grotto_id': 0x0F, 'savewarp_fallback': 0x027E }]],
    ['Grotto',          ['Hyrule Field -> HF Near Market Grotto',                           { 'grotto_id': 0x10, 'entrance': 0x003F, 'content': 0x00, 'scene': 0x51 }],
                        ['HF Near Market Grotto -> Hyrule Field',                           { 'grotto_id': 0x10, 'savewarp_fallback': 0x027E }]],
    ['Grotto',          ['Hyrule Field -> HF Cow Grotto',                                   { 'grotto_id': 0x11, 'entrance': 0x05A8, 'content': 0xE4, 'scene': 0x51 }],
                        ['HF Cow Grotto -> Hyrule Field',                                   { 'grotto_id': 0x11, 'savewarp_fallback': 0x018D }]],
    ['Grotto',          ['Hyrule Field -> HF Inside Fence Grotto',                          { 'grotto_id': 0x12, 'entrance': 0x059C, 'content': 0xE6, 'scene': 0x51 }],
                        ['HF Inside Fence Grotto -> Hyrule Field',                          { 'grotto_id': 0x12, 'savewarp_fallback': 0x0189 }]],
    ['Grotto',          ['Hyrule Field -> HF Open Grotto',                                  { 'grotto_id': 0x13, 'entrance': 0x003F, 'content': 0x03, 'scene': 0x51 }],
                        ['HF Open Grotto -> Hyrule Field',                                  { 'grotto_id': 0x13, 'savewarp_fallback': 0x0189 }]],
    ['Grotto',          ['Hyrule Field -> HF Southeast Grotto',                             { 'grotto_id': 0x14, 'entrance': 0x003F, 'content': 0x22, 'scene': 0x51 }],
                        ['HF Southeast Grotto -> Hyrule Field',                             { 'grotto_id': 0x14, 'savewarp_fallback': 0x0189 }]],
    ['Grotto',          ['Lon Lon Ranch -> LLR Grotto',                                     { 'grotto_id': 0x15, 'entrance': 0x05A4, 'content': 0xFC, 'scene': 0x63 }],
                        ['LLR Grotto -> Lon Lon Ranch',                                     { 'grotto_id': 0x15, 'savewarp_fallback': 0x05D4 }]],
    ['Grotto',          ['SFM Entryway -> SFM Wolfos Grotto',                               { 'grotto_id': 0x16, 'entrance': 0x05B4, 'content': 0xED, 'scene': 0x56 }],
                        ['SFM Wolfos Grotto -> SFM Entryway',                               { 'grotto_id': 0x16, 'savewarp_fallback': 0x00FC }]],
    ['Grotto',          ['Sacred Forest Meadow -> SFM Storms Grotto',                       { 'grotto_id': 0x17, 'entrance': 0x05BC, 'content': 0xEE, 'scene': 0x56 }],
                        ['SFM Storms Grotto -> Sacred Forest Meadow',                       { 'grotto_id': 0x17, 'savewarp_fallback': 0x0600 }]],
    ['Grotto',          ['Sacred Forest Meadow -> SFM Fairy Grotto',                        { 'grotto_id': 0x18, 'entrance': 0x036D, 'content': 0xFF, 'scene': 0x56 }],
                        ['SFM Fairy Grotto -> Sacred Forest Meadow',                        { 'grotto_id': 0x18, 'savewarp_fallback': 0x0600 }]],
    ['Grotto',          ['LW Beyond Mido -> LW Scrubs Grotto',                              { 'grotto_id': 0x19, 'entrance': 0x05B0, 'content': 0xF5, 'scene': 0x5B }],
                        ['LW Scrubs Grotto -> LW Beyond Mido',                              { 'grotto_id': 0x19, 'savewarp_fallback': 0x01A9 }]],
    ['Grotto',          ['Lost Woods -> LW Near Shortcuts Grotto',                          { 'grotto_id': 0x1A, 'entrance': 0x003F, 'content': 0x14, 'scene': 0x5B }],
                        ['LW Near Shortcuts Grotto -> Lost Woods',                          { 'grotto_id': 0x1A, 'savewarp_fallback': 0x04D6 }]],
    ['Grotto',          ['Kokiri Forest -> KF Storms Grotto',                               { 'grotto_id': 0x1B, 'entrance': 0x003F, 'content': 0x2C, 'scene': 0x55 }],
                        ['KF Storms Grotto -> Kokiri Forest',                               { 'grotto_id': 0x1B, 'savewarp_fallback': 0x0286 }]],
    ['Grotto',          ['Zoras Domain -> ZD Storms Grotto',                                { 'grotto_id': 0x1C, 'entrance': 0x036D, 'content': 0xFF, 'scene': 0x58 }],
                        ['ZD Storms Grotto -> Zoras Domain',                                { 'grotto_id': 0x1C, 'savewarp_fallback': 0x0108 }]],
    ['Grotto',          ['GF Entrances Behind Crates -> GF Storms Grotto',                  { 'grotto_id': 0x1D, 'entrance': 0x036D, 'content': 0xFF, 'scene': 0x5D }],
                        ['GF Storms Grotto -> GF Entrances Behind Crates',                  { 'grotto_id': 0x1D, 'savewarp_fallback': 0x0235 }]],
    ['Grotto',          ['GV Fortress Side -> GV Storms Grotto',                            { 'grotto_id': 0x1E, 'entrance': 0x05BC, 'content': 0xF0, 'scene': 0x5A }],
                        ['GV Storms Grotto -> GV Fortress Side',                            { 'grotto_id': 0x1E, 'savewarp_fallback': 0x022D }]],
    ['Grotto',          ['GV Grotto Ledge -> GV Octorok Grotto',                            { 'grotto_id': 0x1F, 'entrance': 0x05AC, 'content': 0xF2, 'scene': 0x5A }],
                        ['GV Octorok Grotto -> GV Grotto Ledge',                            { 'grotto_id': 0x1F, 'savewarp_fallback': 0x0117 }]],
    ['Grotto',          ['LW Beyond Mido -> Deku Theater',                                  { 'grotto_id': 0x20, 'entrance': 0x05C4, 'content': 0xF3, 'scene': 0x5B }],
                        ['Deku Theater -> LW Beyond Mido',                                  { 'grotto_id': 0x20, 'savewarp_fallback': 0x01A9 }]],

    ['Grave',           ['Graveyard -> Graveyard Shield Grave',                             { 'index': 0x004B }],
                        ['Graveyard Shield Grave -> Graveyard',                             { 'index': 0x035D }]],
    ['Grave',           ['Graveyard -> Graveyard Heart Piece Grave',                        { 'index': 0x031C }],
                        ['Graveyard Heart Piece Grave -> Graveyard',                        { 'index': 0x0361 }]],
    ['Grave',           ['Graveyard -> Graveyard Royal Familys Tomb',                       { 'index': 0x002D }],
                        ['Graveyard Royal Familys Tomb -> Graveyard',                       { 'index': 0x050B }]],
    ['Grave',           ['Graveyard -> Graveyard Dampes Grave',                             { 'index': 0x044F }],
                        ['Graveyard Dampes Grave -> Graveyard',                             { 'index': 0x0359 }]],

    ['Overworld',       ['Kokiri Forest -> LW Bridge From Forest',                          { 'index': 0x05E0 }],
                        ['LW Bridge -> Kokiri Forest',                                      { 'index': 0x020D }]],
    ['Overworld',       ['Kokiri Forest -> Lost Woods',                                     { 'index': 0x011E }],
                        ['LW Forest Exit -> Kokiri Forest',                                 { 'index': 0x0286 }]],
    ['Overworld',       ['Lost Woods -> GC Woods Warp',                                     { 'index': 0x04E2 }],
                        ['GC Woods Warp -> Lost Woods',                                     { 'index': 0x04D6 }]],
    ['Overworld',       ['Lost Woods -> Zora River',                                        { 'index': 0x01DD }],
                        ['Zora River -> LW Underwater Entrance',                            { 'index': 0x04DA }]],
    ['Overworld',       ['LW Beyond Mido -> SFM Entryway',                                  { 'index': 0x00FC }],
                        ['SFM Entryway -> LW Beyond Mido',                                  { 'index': 0x01A9 }]],
    ['Overworld',       ['LW Bridge -> Hyrule Field',                                       { 'index': 0x0185 }],
                        ['Hyrule Field -> LW Bridge',                                       { 'index': 0x04DE }]],
    ['Overworld',       ['Hyrule Field -> Lake Hylia',                                      { 'index': 0x0102 }],
                        ['Lake Hylia -> Hyrule Field',                                      { 'index': 0x0189 }]],
    ['Overworld',       ['Hyrule Field -> Gerudo Valley',                                   { 'index': 0x0117 }],
                        ['Gerudo Valley -> Hyrule Field',                                   { 'index': 0x018D }]],
    ['Overworld',       ['Hyrule Field -> Market Entrance',                                 { 'index': 0x0276 }],
                        ['Market Entrance -> Hyrule Field',                                 { 'index': 0x01FD }]],
    ['Overworld',       ['Hyrule Field -> Kakariko Village',                                { 'index': 0x00DB }],
                        ['Kakariko Village -> Hyrule Field',                                { 'index': 0x017D }]],
    ['Overworld',       ['Hyrule Field -> ZR Front',                                        { 'index': 0x00EA }],
                        ['ZR Front -> Hyrule Field',                                        { 'index': 0x0181 }]],
    ['Overworld',       ['Hyrule Field -> Lon Lon Ranch',                                   { 'index': 0x0157 }],
                        ['Lon Lon Ranch -> Hyrule Field',                                   { 'index': 0x01F9 }]],
    ['Overworld',       ['Lake Hylia -> Zoras Domain',                                      { 'index': 0x0328 }],
                        ['Zoras Domain -> Lake Hylia',                                      { 'index': 0x0560 }]],
    ['Overworld',       ['GV Fortress Side -> Gerudo Fortress',                             { 'index': 0x0129 }],
                        ['Gerudo Fortress -> GV Fortress Side',                             { 'index': 0x022D }]],
    ['Overworld',       ['GF Outside Gate -> Wasteland Near Fortress',                      { 'index': 0x0130 }],
                        ['Wasteland Near Fortress -> GF Outside Gate',                      { 'index': 0x03AC }]],
    ['Overworld',       ['Wasteland Near Colossus -> Desert Colossus',                      { 'index': 0x0123 }],
                        ['Desert Colossus -> Wasteland Near Colossus',                      { 'index': 0x0365 }]],
    ['Overworld',       ['Market Entrance -> Market',                                       { 'index': 0x00B1 }],
                        ['Market -> Market Entrance',                                       { 'index': 0x0033 }]],
    ['Overworld',       ['Market -> Castle Grounds',                                        { 'index': 0x0138 }],
                        ['Castle Grounds -> Market',                                        { 'index': 0x025A }]],
    ['Overworld',       ['Market -> ToT Entrance',                                          { 'index': 0x0171 }],
                        ['ToT Entrance -> Market',                                          { 'index': 0x025E }]],
    ['Overworld',       ['Kakariko Village -> Graveyard',                                   { 'index': 0x00E4 }],
                        ['Graveyard -> Kakariko Village',                                   { 'index': 0x0195 }]],
    ['Overworld',       ['Kak Behind Gate -> Death Mountain',                               { 'index': 0x013D }],
                        ['Death Mountain -> Kak Behind Gate',                               { 'index': 0x0191 }]],
    ['Overworld',       ['Death Mountain -> Goron City',                                    { 'index': 0x014D }],
                        ['Goron City -> Death Mountain',                                    { 'index': 0x01B9 }]],
    ['Overworld',       ['GC Darunias Chamber -> DMC Lower Local',                          { 'index': 0x0246 }],
                        ['DMC Lower Nearby -> GC Darunias Chamber',                         { 'index': 0x01C1 }]],
    ['Overworld',       ['Death Mountain Summit -> DMC Upper Local',                        { 'index': 0x0147 }],
                        ['DMC Upper Nearby -> Death Mountain Summit',                       { 'index': 0x01BD }]],
    ['Overworld',       ['ZR Behind Waterfall -> Zoras Domain',                             { 'index': 0x0108 }],
                        ['Zoras Domain -> ZR Behind Waterfall',                             { 'index': 0x019D }]],
    ['Overworld',       ['ZD Behind King Zora -> Zoras Fountain',                           { 'index': 0x0225 }],
                        ['Zoras Fountain -> ZD Behind King Zora',                           { 'index': 0x01A1 }]],

    ['OverworldOneWay', ['GV Lower Stream -> Lake Hylia',                                   { 'index': 0x0219 }]],

    ['OwlDrop',         ['LH Owl Flight -> Hyrule Field',                                   { 'index': 0x027E, 'addresses': [0xAC9F26] }]],
    ['OwlDrop',         ['DMT Owl Flight -> Kak Impas Rooftop',                             { 'index': 0x0554, 'addresses': [0xAC9EF2] }]],

    ['Spawn',           ['Child Spawn -> KF Links House',                                   { 'index': 0x00BB, 'addresses': [0xB06342] }]],
    ['Spawn',           ['Adult Spawn -> Temple of Time',                                   { 'index': 0x05F4, 'addresses': [0xB06332] }]],

    ['WarpSong',        ['Minuet of Forest Warp -> Sacred Forest Meadow',                   { 'index': 0x0600, 'addresses': [0xBF023C] }]],
    ['WarpSong',        ['Bolero of Fire Warp -> DMC Central Local',                        { 'index': 0x04F6, 'addresses': [0xBF023E] }]],
    ['WarpSong',        ['Serenade of Water Warp -> Lake Hylia',                            { 'index': 0x0604, 'addresses': [0xBF0240] }]],
    ['WarpSong',        ['Requiem of Spirit Warp -> Desert Colossus',                       { 'index': 0x01F1, 'addresses': [0xBF0242] }]],
    ['WarpSong',        ['Nocturne of Shadow Warp -> Graveyard Warp Pad Region',            { 'index': 0x0568, 'addresses': [0xBF0244] }]],
    ['WarpSong',        ['Prelude of Light Warp -> Temple of Time',                         { 'index': 0x05F4, 'addresses': [0xBF0246] }]],

    ['BlueWarp',        ['Queen Gohma Boss Room -> KF Outside Deku Tree',                   { 'index': 0x0457, 'addresses': [0xAC93A2, 0xCA3142] }]],
    ['BlueWarp',        ['King Dodongo Boss Room -> Death Mountain',                        { 'index': 0x047A, 'addresses': [0xAC9336, 0xCA30CA] }]],
    ['BlueWarp',        ['Barinade Boss Room -> Zoras Fountain',                            { 'index': 0x010E, 'addresses': [0xAC936A, 0xCA31B2] }]],
    ['BlueWarp',        ['Phantom Ganon Boss Room -> Sacred Forest Meadow',                 { 'index': 0x0608, 'addresses': [0xAC9F96, 0xCA3D66, 0xCA3D5A], 'child_index': 0x0600 }]],
    ['BlueWarp',        ['Volvagia Boss Room -> DMC Central Local',                         { 'index': 0x0564, 'addresses': [0xACA516, 0xCA3DF2, 0xCA3DE6], 'child_index': 0x04F6 }]],
    ['BlueWarp',        ['Morpha Boss Room -> Lake Hylia',                                  { 'index': 0x060C, 'addresses': [0xAC995A, 0xCA3E82, 0xCA3E76], 'child_index': 0x0604 }]],
    ['BlueWarp',        ['Bongo Bongo Boss Room -> Graveyard Warp Pad Region',              { 'index': 0x0580, 'addresses': [0xACA496, 0xCA3FA2, 0xCA3F96], 'child_index': 0x0568 }]],
    ['BlueWarp',        ['Twinrova Boss Room -> Desert Colossus',                           { 'index': 0x0610, 'addresses': [0xACA402, 0xCA3F12, 0xCA3F06], 'child_index': 0x01F1 }]],

    ['Extra',           ['ZD Eyeball Frog Timeout -> Zoras Domain',                         { 'index': 0x0153 }]],
    ['Extra',           ['ZR Top of Waterfall -> Zora River',                               { 'index': 0x0199 }]],
];

export default entrance_shuffle_table;