import type { SettingsDictionary } from "./SettingsList.js"

export const rsl_preset_template: SettingsDictionary = {
    "world_count": 1,
    "graphplugin_song_melodies": {},
    "show_seed_info": true,
    "user_message": "RSL Season 6",
    "create_spoiler": true,
    "randomize_settings": false,
    "logic_rules": "glitchless",
    "reachable_locations": "all",
    "triforce_hunt": false,
    "triforce_count_per_world": 100,
    "triforce_goal_per_world": 100,
    "lacs_condition": "vanilla",
    "lacs_medallions": 6,
    "lacs_stones": 3,
    "lacs_rewards": 9,
    "lacs_tokens": 100,
    "lacs_hearts": 20,
    "bridge": "dungeons",
    "bridge_medallions": 6,
    "bridge_stones": 3,
    "bridge_rewards": 9,
    "bridge_tokens": 100,
    "bridge_hearts": 20,
    "trials_random": false,
    "trials": 6,
    "graphplugin_trials_specific": [
        "Forest",
        "Fire",
        "Water",
        "Spirit",
        "Shadow",
        "Light"
    ],
    "shuffle_ganon_bosskey": "rewards",
    "ganon_bosskey_medallions": 6,
    "ganon_bosskey_stones": 3,
    "ganon_bosskey_rewards": 9,
    "ganon_bosskey_tokens": 100,
    "ganon_bosskey_hearts": 20,
    "shuffle_bosskeys": "keysanity",
    "shuffle_smallkeys": "keysanity",
    "shuffle_hideoutkeys": "keysanity",
    "shuffle_tcgkeys": "keysanity",
    "key_rings_choice": "off",
    "key_rings": [],
    "keyring_give_bk": false,
    "shuffle_silver_rupees": "anywhere",
    "silver_rupee_pouches_choice": "all",
    "silver_rupee_pouches": [
        "Dodongo's Cavern Staircase",
        "Ice Cavern Spinning Scythe",
        "Ice Cavern Push Block",
        "Bottom of the Well Basement",
        "Shadow Temple Scythe Shortcut",
        "Shadow Temple Invisible Blades",
        "Shadow Temple Huge Pit",
        "Shadow Temple Invisible Spikes",
        "Gerudo Training Ground Slopes",
        "Gerudo Training Ground Lava",
        "Gerudo Training Ground Water",
        "Spirit Temple Child Early Torches",
        "Spirit Temple Adult Boulders",
        "Spirit Temple Lobby and Lower Adult",
        "Spirit Temple Sun Block",
        "Spirit Temple Adult Climb",
        "Ganon's Castle Spirit Trial",
        "Ganon's Castle Light Trial",
        "Ganon's Castle Fire Trial",
        "Ganon's Castle Shadow Trial",
        "Ganon's Castle Water Trial",
        "Ganon's Castle Forest Trial"
    ],
    "shuffle_mapcompass": "keysanity",
    "enhance_map_compass": false,
    "open_forest": "closed_deku",
    "open_kakariko": "zelda",
    "open_door_of_time": false,
    "zora_fountain": "closed",
    "gerudo_fortress": "normal",
    "dungeon_shortcuts_choice": "off",
    "dungeon_shortcuts": [],
    "starting_age": "child",
    "mq_dungeons_mode": "specific",
    "mq_dungeons_specific": [],
    "mq_dungeons_count": 0,
    "empty_dungeons_mode": "none",
    "empty_dungeons_specific": [],
    "empty_dungeons_count": 2,
    "shuffle_interior_entrances": "all",
    "shuffle_hideout_entrances": false,
    "shuffle_grotto_entrances": true,
    "shuffle_dungeon_entrances": "all",
    "shuffle_bosses": "full",
    "shuffle_overworld_entrances": true,
    "shuffle_gerudo_valley_river_exit": true,
    "owl_drops": true,
    "warp_songs": true,
    "spawn_positions": [
        "adult",
        "child"
    ],
    "free_bombchu_drops": true,
    "one_item_per_dungeon": false,
    "shuffle_song_items": "any",
    "shopsanity": "4",
    "shopsanity_prices": "random",
    "tokensanity": "all",
    "shuffle_scrubs": "random",
    "shuffle_child_trade": [
        "Weird Egg",
        "Chicken",
        "Zeldas Letter",
        "Keaton Mask",
        "Skull Mask",
        "Spooky Mask",
        "Bunny Hood",
        "Goron Mask",
        "Zora Mask",
        "Gerudo Mask",
        "Mask of Truth"
    ],
    "shuffle_freestanding_items": "all",
    "shuffle_pots": "all",
    "shuffle_crates": "all",
    "shuffle_cows": true,
    "shuffle_beehives": false,
    "shuffle_wonderitems": false,
    "shuffle_kokiri_sword": true,
    "shuffle_ocarinas": true,
    "shuffle_gerudo_card": true,
    "shuffle_beans": true,
    "shuffle_expensive_merchants": true,
    "shuffle_frog_song_rupees": true,
    "shuffle_individual_ocarina_notes": false,
    "shuffle_loach_reward": "off",
    "logic_no_night_tokens_without_suns_song": false,
    "disabled_locations": [],
    "allowed_tricks": [
        "logic_fewer_tunic_requirements",
        "logic_grottos_without_agony",
        "logic_child_deadhand",
        "logic_man_on_roof",
        "logic_dc_jump",
        "logic_rusted_switches",
        "logic_windmill_poh",
        "logic_crater_bean_poh_with_hovers",
        "logic_forest_vines",
        "logic_lens_botw",
        "logic_lens_castle",
        "logic_lens_gtg",
        "logic_lens_shadow",
        "logic_lens_spirit",
        "logic_visible_collisions",
        "logic_deku_b1_webs_with_bow",
        "logic_lens_gtg_mq",
        "logic_lens_jabu_mq",
        "logic_lens_shadow_mq",
        "logic_lens_spirit_mq",
        "logic_lens_shadow_mq",
        "logic_lens_shadow_mq_platform",
        "logic_lens_shadow",
        "logic_lens_shadow_platform",
        "logic_lens_shadow_mq_dead_hand",
        "logic_lens_bongo",
        "logic_lens_castle_mq"
    ],
    "starting_equipment": [
        "deku_shield"
    ],
    "starting_songs": [],
    "starting_inventory": [
        "ocarina",
        "zeldas_letter"
    ],
    "start_with_consumables": true,
    "start_with_rupees": true,
    "starting_hearts": 3,
    "no_escape_sequence": false,
    "no_guard_stealth": true,
    "no_epona_race": false,
    "skip_some_minigame_phases": true,
    "complete_mask_quest": false,
    "useful_cutscenes": false,
    "fast_chests": true,
    "free_scarecrow": false,
    "fast_bunny_hood": true,
    "auto_equip_masks": false,
    "plant_beans": false,
    "chicken_count_random": false,
    "chicken_count": 7,
    "big_poe_count_random": false,
    "big_poe_count": 10,
    "easier_fire_arrow_entry": false,
    "fae_torch_count": 3,
    "ruto_already_f1_jabu": false,
    "ocarina_songs": "off",
    "correct_chest_appearances": "both",
    "minor_items_as_major_chest": [
        "bombchus",
        "shields",
        "capacity"
    ],
    "invisible_chests": false,
    "correct_potcrate_appearances": "textures_content",
    "key_appearance_match_dungeon": false,
    "clearer_hints": true,
    "hints": "always",
    "hint_dist": "chaos",
    "item_hints": [],
    "hint_dist_user": {},
    "misc_hints": [
        "altar",
        "dampe_diary",
        "ganondorf",
        "warp_songs_and_owls",
        "mask_shop",
        "unique_merchants"
    ],
    "text_shuffle": "none",
    "damage_multiplier": "normal",
    "deadly_bonks": "none",
    "no_collectible_hearts": false,
    "starting_tod": "default",
    "blue_fire_arrows": true,
    "fix_broken_drops": false,
    "item_pool_value": "balanced",
    "junk_ice_traps": "off",
    "ice_trap_appearance": "anything",
    "adult_trade_shuffle": true,
    "adult_trade_start": [
        "Pocket Egg",
        "Pocket Cucco",
        "Cojiro",
        "Odd Mushroom",
        "Odd Potion",
        "Poachers Saw",
        "Broken Sword",
        "Prescription",
        "Eyeball Frog",
        "Eyedrops",
        "Claim Check"
    ]
}